version: "3.9"

services:
  blog:
    container_name: blog
    image: "jonny5592/blog:main"
    ports:
      - "3000"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000 || exit 1"
      interval: 10s
      timeout: 10s
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.blog.rule=Host(`jean-marc.io`, `www.jean-marc.io`)"
        - "traefik.http.routers.blog.tls=true"
        - "traefik.http.routers.blog.tls.certresolver=letsencrypt"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.blog.loadbalancer.server.port=3000"
    networks:
      - traefik

networks:
  traefik:
    external: true