name: Build, Push and Deploy

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build for multiple platforms
      # - name: Setup QEMU
      #   id: qemu
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     image: tonistiigi/binfmt:latest
      #     platforms: all

      # Configure the Docker Image Meta Data
      # - name: Docker Meta Data
      #   id: docker_meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: jonny5592/blog

      - name: Set Globals
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo "TRIVY_VERSION=0.65.0" >> "$GITHUB_ENV"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build Docker Image
        if: github.event_name != 'pull_request'
        id: build_docker_image
        run: |
          DOCKER_IMAGE=jonny5592/blog:${SHORT_SHA}

          echo "Building Docker Image ${DOCKER_IMAGE}"
          docker build . -t ${DOCKER_IMAGE}

          echo "image=$DOCKER_IMAGE" >> "$GITHUB_OUTPUT"

      - name: Scan Docker Image
        if: github.event_name != 'pull_request'
        id: scan_docker_image
        run: |
          IMAGE="${{ steps.build_docker_image.outputs.image }}"
          SBOM_FILE=sbom-image-${SHORT_SHA}.cdx.json

          echo "Scanning Docker Image using Trivy v${TRIVY_VERSION}"
          docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:${TRIVY_VERSION} image \
            --skip-dirs /usr/local/lib,/usr/src/app,/opt,/app \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            ${IMAGE}

          echo "Generating SBOM..."
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "${{ github.workspace }}:/project" \
            aquasec/trivy:${TRIVY_VERSION} image \
              --format cyclonedx \
              --scanners vuln \
              --output /project/${SBOM_FILE} \
              ${IMAGE}

          echo "sbom_file=$SBOM_FILE" >> "$GITHUB_OUTPUT"

      - name: Scan Dependencies
        if: github.event_name != 'pull_request'
        id: scan_dependencies
        run: |
          SBOM_FILE=sbom-deps-${SHORT_SHA}.cdx.json

          echo "Scanning Dependencies using Trivy v${TRIVY_VERSION}"
          docker run --rm \
            -v "${{ github.workspace }}:/project" \
            aquasec/trivy:${TRIVY_VERSION} fs \
              --severity CRITICAL,HIGH \
              --exit-code 1 \
              /project

          echo "Generating SBOM..."
          docker run --rm \
            -v "${{ github.workspace }}:/project" \
            aquasec/trivy:${TRIVY_VERSION} fs \
              --format cyclonedx \
              --scanners vuln \
              --output /project/${SBOM_FILE} \
              /project

          echo "sbom_file=$SBOM_FILE" >> "$GITHUB_OUTPUT"

      - name: Upload SBOM artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: sboms-${{ env.SHORT_SHA }}
          path: |
            ${{ steps.scan_docker_image.outputs.sbom_file }}
            ${{ steps.scan_dependencies.outputs.sbom_file }}

      # Login to DockerHub
      # - name: Login to DockerHub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build Image and push to DockerHub Repository
      # - name: Build and Push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.docker_meta.outputs.tags }}
      #     labels: ${{ steps.docker_meta.outputs.labels }}

  # deploy:
  #   runs-on: self-hosted
  #   needs: build_and_push
  #   steps:
  #     # Checkout Repository
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Login to DockerHub
  #     - name: Login to DockerHub
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  #     # Deploy Docker Container
  #     - name: Pull Docker Image and Run Docker Container
  #       run: |
  #         docker pull jonny5592/blog:latest
  #         docker stack deploy -c docker-compose.yml --prune --with-registry-auth blog
