name: Build, Push and Deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Build for multiple platforms
      - name: Setup QEMU
        id: qemu 
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      # Configure the Docker Image Meta Data
      - name: Docker Meta Data
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: jonny5592/blog
      
      # Login to DockerHub
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build Image and push to DockerHub Repository
      - name: Build and Push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}